import { Serie } from './Serie.js';
export const series = [
    new Serie(1, "Breaking Bad", "AMC", 5, "Set and filmed in Albuquerque, New Mexico, the series tells the story of Walter White, a struggling and depressed high school chemistry teacher who is diagnosed with lung cancer", "https://ce.amc.com/series/breaking-bad", "https://th.bing.com/th/id/OIP.6erJ3FK7pUcbUS31jXNXywHaHa?w=167&h=180&c=7&r=0&o=5&dpr=2&pid=1.7"),
    new Serie(2, "Orange Is the New Black", "Netflix", 6, "The series begins revolving around Piper Chapman, a woman in her thirties living in New York City who is sentenced to 15 months in Litchfield Penitentiary", "https://www.netflix.com/co/title/70242311", "https://www.themoviedb.org/t/p/original/z8Mg3YVZGd1iSnoDinEAoh9WTck.jpg"),
    new Serie(3, "Game of Thrones", "HBO", 7, "American fantasy drama", "https://www.hbo.com/game-of-thrones", "https://th.bing.com/th/id/R.bc36089bad03fb3d9fd9c730f2ee2693?rik=63h7mMv1qCyY2w&riu=http%3a%2f%2fwww.herebegeeks.com%2fwp-content%2fuploads%2f2011%2f08%2fgame_of_thrones.jpg&ehk=S9%2b3D92oKA5Ana6aUcqFlDp%2bQEH2IChHKs1bJbFmEM4%3d&risl=&pid=ImgRaw&r=0"),
    new Serie(4, "The Big Bang Theory", "CBS", 12, "Leonard and Sheldon are brilliant physicists—geniuses in the laboratory but socially challenged everywhere else. Enter beautiful, street-smart neighbor Penny, who aims to teach them a thing or two about life. Despite their on-again, off-again relationship in the past, Leonard and Penny have finally gotten married. Even Sheldon has found a female companion, entering into a relationship agreement with neurobiologist Amy Farrah Fowler, and he recently took their relationship to the next level by marrying her after a long courtship. In their free time, Leonard and Sheldon enjoy fantasy role-playing games with their ever-expanding universe of friends, including fellow scientists Koothrappali, Wolowitz, and Wolowitz’s adorable microbiologist wife, Bernadette, who is adjusting to life with their two children.", "https://www.cbs.com/", "https://www.themoviedb.org/t/p/original/euKFiO5M125rpngFRBbSW83beeI.jpg"),
    new Serie(5, "Sherlock", "BBC", 4, "Sherlock depicts consulting detective Sherlock Holmes (Benedict Cumberbatch) solving various mysteries in modern-day London. Holmes is assisted by his flatmate and friend, Dr John Watson (Martin Freeman), who has returned from military service in Afghanistan with the Royal Army Medical Corps", "https://www.bbc.co.uk/programmes/b018ttws", "https://th.bing.com/th/id/R.fd1058d507a2493cdbbc7725fdfdf7be?rik=LGGsA273XXmENw&riu=http%3a%2f%2f1.bp.blogspot.com%2f-AkGGO8kGhTw%2fTbVLG7xSm1I%2fAAAAAAAAAT0%2frczUdsMWAnM%2fs1600%2fSherlock1024.jpg&ehk=mgVEmFvmUbsg0gcuEGpA0CV5sNgUNFaxnI%2fCsxNXb2Q%3d&risl=&pid=ImgRaw&r=0"),
    new Serie(6, "A Very English Scandal", "BBC", 2, "A Very English Scandal is a fact-based three-part British television comedy-drama miniseries based on John Preston's book of the same name.", "https://www.bbc.co.uk/programmes/p065smy4", "https://images-na.ssl-images-amazon.com/images/I/81aYyVYiIHL._RI_.jpg"),
];
